parameters:
    replay_initial_id: !php/const AE\ConnectBundle\Bayeux\Extension\ReplayExtension::REPLAY_SAVED
services:
    AE\ConnectBundle\Bayeux\Transport\LongPollingTransport:
        autowire: true
    AE\ConnectBundle\Bayeux\AuthProvider\LoginProvider:
        autowire: true
        arguments:
            $clientId: "%env(SF_CLIENT_ID)%"
            $clientSecret: "%env(SF_CLIENT_SECRET)%"
            $username: "%env(SF_USER)%"
            $password: "%env(SF_PASS)%"
            $url: "https://login.salesforce.com"
    AE\ConnectBundle\Bayeux\Transport\AbstractClientTransport: '@AE\ConnectBundle\Bayeux\Transport\LongPollingTransport'
    AE\ConnectBundle\Bayeux\AuthProvider\AuthProviderInterface: '@AE\ConnectBundle\Bayeux\AuthProvider\LoginProvider'
    AE\ConnectBundle\Bayeux\BayeuxClient:
        public: true
        autowire: true
        arguments:
            $url: "%env(SF_URL)%"
    AE\ConnectBundle\Bayeux\Extension\ReplayExtension:
        autowire: true
        arguments:
            $replayId: "%replay_initial_id%"
        tags:
            - { name: 'ae_connect.extension' }
