services:
    _instanceof:
        AE\ConnectBundle\Connection\ConnectionInterface:
            tags: ['ae_connect.connection']
        AE\ConnectBundle\Salesforce\Inbound\SalesforceConsumerInterface:
            tags: ['ae_connect.consumer']

    Psr\Log\SyncLogger: '@Psr\Log\LoggerInterface'
    Psr\Log\InboundLogger: '@Psr\Log\LoggerInterface'
    Psr\Log\OutboundLogger: '@Psr\Log\LoggerInterface'

    AE\SalesforceRestSdk\Bayeux\Transport\LongPollingTransport: ~
    AE\SalesforceRestSdk\Bayeux\Transport\AbstractClientTransport: '@AE\SalesforceRestSdk\Bayeux\Transport\LongPollingTransport'
    AE\ConnectBundle\Manager\ConnectionManager:
        public: true
    AE\ConnectBundle\Manager\ConnectionManagerInterface:
        alias: 'AE\ConnectBundle\Manager\ConnectionManager'
        public: true
    ae_connect.connection_manager:
        alias: 'AE\ConnectBundle\Manager\ConnectionManager'
        public: true
    AE\SalesforceRestSdk\Bayeux\Extension\SfdcExtension:
        tags: ['ae_connect.extension']
    AE\ConnectBundle\Serializer\CompositeSObjectSubscriber:
        tags:
            -
                name: 'jms_serializer.subscribing_handler'
                format: 'json'
                type: 'AE\SalesforceRestSdk\Model\Rest\Composite\CompositeSObject'
    AE\SalesforceRestSdk\Serializer\SObjectHandler:
        tags:
            -
                name: 'jms_serializer.subscribing_handler'
                format: 'json'
                type: 'AE\SalesforceRestSdk\Model\SObject'
    AE\ConnectBundle\Salesforce\Outbound\Compiler\SObjectCompiler:
        $connectionManager: '@AE\ConnectBundle\Manager\ConnectionManagerInterface'
        $registry: '@Symfony\Bridge\Doctrine\RegistryInterface'
        $fieldCompiler: '@AE\ConnectBundle\Salesforce\Compiler\FieldCompiler'
        $validator: '@Symfony\Component\Validator\Validator\ValidatorInterface'
        $logger: '@Psr\Log\OutboundLogger'
    AE\ConnectBundle\Salesforce\SalesforceConnector:
        $sObjectCompiler: '@AE\ConnectBundle\Salesforce\Outbound\Compiler\SObjectCompiler'
        $entityCompiler: '@AE\ConnectBundle\Salesforce\Inbound\Compiler\EntityCompiler'
        $producer: '@enqueue.client.ae_connect.producer'
        $serializer: '@JMS\Serializer\SerializerInterface'
        $registry: '@Symfony\Bridge\Doctrine\RegistryInterface'
        $logger: '@Psr\Log\OutboundLogger'
    AE\ConnectBundle\Salesforce\Outbound\Enqueue\OutboundProcessor:
        arguments:
            $queue: '@AE\ConnectBundle\Salesforce\Outbound\Queue\OutboundQueue'
            $serializer: '@JMS\Serializer\SerializerInterface'
            $connectionManager: '@AE\ConnectBundle\Manager\ConnectionManagerInterface'
        tags:
            -
                name: 'enqueue.transport.processor'
                transport: 'ae_connect'
    AE\ConnectBundle\Salesforce\Outbound\Queue\OutboundQueue:
        $cache: '@doctrine_cache.providers.ae_connect_outbound_queue'
        $connectionManager: '@AE\ConnectBundle\Manager\ConnectionManagerInterface'
        $registry: '@Symfony\Bridge\Doctrine\RegistryInterface'
        $fieldCompiler: '@AE\ConnectBundle\Salesforce\Compiler\FieldCompiler'
        $logger: '@Psr\Log\OutboundLogger'
    AE\ConnectBundle\Doctrine\Subscriber\UuidSubscriber:
        arguments:
            $connectionManager: '@AE\ConnectBundle\Manager\ConnectionManagerInterface'
        tags: ['doctrine.event_subscriber']
    AE\ConnectBundle\Doctrine\EntityLocater:
        arguments:
            $registry: '@Symfony\Bridge\Doctrine\RegistryInterface'
            $fieldCompiler: '@AE\ConnectBundle\Salesforce\Compiler\FieldCompiler'
        calls:
            - ['setLogger', ['@Psr\Log\SyncLogger']]
    AE\ConnectBundle\Salesforce\Compiler\FieldCompiler:
        $registry: '@Symfony\Bridge\Doctrine\RegistryInterface'
        $transformer: '@AE\ConnectBundle\Salesforce\Transformer\TransformerInterface'
    AE\ConnectBundle\Salesforce\Compiler\ObjectCompiler:
        arguments:
            $fieldCompiler: '@AE\ConnectBundle\Salesforce\Compiler\FieldCompiler'
            $serializer: '@JMS\Serializer\SerializerInterface'
            $registry: '@Symfony\Bridge\Doctrine\RegistryInterface'
    AE\ConnectBundle\Salesforce\Inbound\Compiler\EntityCompiler:
        $connectionManager: '@AE\ConnectBundle\Manager\ConnectionManagerInterface'
        $validator: '@Symfony\Component\Validator\Validator\ValidatorInterface'
        $fieldCompiler: '@AE\ConnectBundle\Salesforce\Compiler\FieldCompiler'
        $entityLocater: '@AE\ConnectBundle\Doctrine\EntityLocater'
        $registry: '@Symfony\Bridge\Doctrine\RegistryInterface'
        $logger: '@Psr\Log\InboundLogger'
    AE\ConnectBundle\Salesforce\Inbound\SObjectConsumer:
        arguments:
            $connector: '@AE\ConnectBundle\Salesforce\SalesforceConnector'
        calls:
            - ['setLogger', ['@Psr\Log\InboundLogger']]
    AE\ConnectBundle\Salesforce\Inbound\Polling\PollingService:
        $cache: '@doctrine_cache.providers.ae_connect_polling'
        $connectionManager: '@AE\ConnectBundle\Manager\ConnectionManagerInterface'
        $connector: '@AE\ConnectBundle\Salesforce\SalesforceConnector'
    AE\ConnectBundle\Salesforce\Bulk\EntityTreeMaker:
        $registry: '@Symfony\Bridge\Doctrine\RegistryInterface'
    AE\ConnectBundle\Salesforce\Bulk\SObjectTreeMaker:
        $registry: '@Symfony\Bridge\Doctrine\RegistryInterface'
    AE\ConnectBundle\Salesforce\Bulk\BulkPreprocessor:
        $entityLocater: '@AE\ConnectBundle\Doctrine\EntityLocater'
    AE\ConnectBundle\Salesforce\Bulk\BulkApiProcessor:
        arguments:
            $preprocessor: '@AE\ConnectBundle\Salesforce\Bulk\BulkPreprocessor'
            $connector: '@AE\ConnectBundle\Salesforce\SalesforceConnector'
            $progress: '@AE\ConnectBundle\Salesforce\Bulk\BulkProgress'
            $batchSize: '%ae_connect.db_batch_size%'
        calls:
            - ['setLogger', ['@Psr\Log\SyncLogger']]
    AE\ConnectBundle\Salesforce\Bulk\CompositeApiProcessor:
        arguments:
            $preprocessor: '@AE\ConnectBundle\Salesforce\Bulk\BulkPreprocessor'
            $connector: '@AE\ConnectBundle\Salesforce\SalesforceConnector'
            $progress: '@AE\ConnectBundle\Salesforce\Bulk\BulkProgress'
            $batchSize: '%ae_connect.db_batch_size%'
        calls:
            - ['setLogger', ['@Psr\Log\SyncLogger']]
    AE\ConnectBundle\Salesforce\Bulk\InboundBulkQueue:
        $treeMaker: '@AE\ConnectBundle\Salesforce\Bulk\SObjectTreeMaker'
        $bulkApiProcessor: '@AE\ConnectBundle\Salesforce\Bulk\BulkApiProcessor'
        $compositeApiProcessor: '@AE\ConnectBundle\Salesforce\Bulk\CompositeApiProcessor'
        $progress: '@AE\ConnectBundle\Salesforce\Bulk\BulkProgress'
        $logger: '@Psr\Log\InboundLogger'
    AE\ConnectBundle\Salesforce\Bulk\OutboundBulkQueue:
        $compiler: '@AE\ConnectBundle\Salesforce\Outbound\Compiler\SObjectCompiler'
        $registry: '@Symfony\Bridge\Doctrine\RegistryInterface'
        $treeMaker: '@AE\ConnectBundle\Salesforce\Bulk\EntityTreeMaker'
        $outboundQueue: '@AE\ConnectBundle\Salesforce\Outbound\Queue\OutboundQueue'
        $reader: '@Doctrine\Common\Annotations\Reader'
        $progress: '@AE\ConnectBundle\Salesforce\Bulk\BulkProgress'
        $batchSize: '%ae_connect.db_batch_size%'
        $logger: '@Psr\Log\OutboundLogger'
    AE\ConnectBundle\Salesforce\Bulk\SfidReset:
        $registry: '@Symfony\Bridge\Doctrine\RegistryInterface'
        $treeMaker: '@AE\ConnectBundle\Salesforce\Bulk\SObjectTreeMaker'
    AE\ConnectBundle\Salesforce\Bulk\BulkDataProcessor:
        $connectionManager: '@AE\ConnectBundle\Manager\ConnectionManagerInterface'
        $inboundBulkQueue: '@AE\ConnectBundle\Salesforce\Bulk\InboundBulkQueue'
        $outboundBulkQueue: '@AE\ConnectBundle\Salesforce\Bulk\OutboundBulkQueue'
        $sfidReset: '@AE\ConnectBundle\Salesforce\Bulk\SfidReset'
        $connector: '@AE\ConnectBundle\Salesforce\SalesforceConnector'
    AE\ConnectBundle\Salesforce\Bulk\InboundQueryProcessor:
        $bulkApiProcessor: '@AE\ConnectBundle\Salesforce\Bulk\BulkApiProcessor'
        $compositeApiProcessor: '@AE\ConnectBundle\Salesforce\Bulk\CompositeApiProcessor'
        $progress: '@AE\ConnectBundle\Salesforce\Bulk\BulkProgress'
    AE\ConnectBundle\Command\BulkCommand:
        arguments:
            $processor: '@AE\ConnectBundle\Salesforce\Synchronize\Sync'
            $dispatcher: '@Symfony\Component\EventDispatcher\EventDispatcherInterface'
        tags: ['console.command']
    AE\ConnectBundle\Command\ConsumeCommand:
        arguments:
            $container: '@service_container'
            $driver: '@enqueue.client.ae_connect.driver'
            $queue: '@AE\ConnectBundle\Salesforce\Outbound\Queue\OutboundQueue'
        tags: ['console.command']
    AE\ConnectBundle\Command\ListenCommand:
        arguments:
            $connectionManager: '@AE\ConnectBundle\Manager\ConnectionManagerInterface'
            $consumer: '@AE\ConnectBundle\Salesforce\Inbound\SObjectConsumer'
            $logger: '@?Psr\Log\InboundLogger'
        tags: ['console.command']
    AE\ConnectBundle\Command\PollCommand:
        arguments:
            $polling: '@AE\ConnectBundle\Salesforce\Inbound\Polling\PollingService'
        tags: ['console.command']
    AE\ConnectBundle\Command\DebugConnectionsCommand:
        arguments:
            $connectionManager: '@AE\ConnectBundle\Manager\ConnectionManagerInterface'
        tags: ['console.command']
    AE\ConnectBundle\Command\DebugMetadataCommand:
        arguments:
            $connectionManager: '@AE\ConnectBundle\Manager\ConnectionManagerInterface'
        tags: ['console.command']
    AE\ConnectBundle\Command\DebugStreamingCommand:
        arguments:
            $connectionManager: '@AE\ConnectBundle\Manager\ConnectionManagerInterface'
            $sfdcExtension: '@AE\SalesforceRestSdk\Bayeux\Extension\SfdcExtension'
            $logger: '@?Psr\Log\SyncLogger'
        calls:
            - ['setContainer', ['@service_container']]
        tags: ['console.command']
    AE\ConnectBundle\Command\QueryImportCommand:
        arguments:
            $connectionManager: '@AE\ConnectBundle\Manager\ConnectionManagerInterface'
            $processor: '@AE\ConnectBundle\Salesforce\Bulk\InboundQueryProcessor'
            $dispatcher: '@Symfony\Component\EventDispatcher\EventDispatcherInterface'
        tags: ['console.command']
    AE\ConnectBundle\Driver\DbalConnectionDriver:
        arguments:
            $connectionManager: '@AE\ConnectBundle\Manager\ConnectionManagerInterface'
            $registry: '@Symfony\Bridge\Doctrine\RegistryInterface'
            $pollingService: '@AE\ConnectBundle\Salesforce\Inbound\Polling\PollingService'
            $logger: '@?Psr\Log\SyncLogger'
        public: true
    AE\ConnectBundle\Salesforce\Bulk\BulkProgress:
        $dispatcher: '@Symfony\Component\EventDispatcher\EventDispatcherInterface'
