services:
    AE\ConnectBundle\Salesforce\Synchronize\Sync:
        autowire: true
        autoconfigure: true

    AE\ConnectBundle\Salesforce\Synchronize\Handlers\FindConnection:
        autowire: true
        autoconfigure: true
        tags:
            - { name: kernel.event_listener, event: aeconnect.initial, method: process }

    AE\ConnectBundle\Salesforce\Synchronize\Handlers\RegisterModules:
        autowire: true
        autoconfigure: true
        tags:
            - { name: kernel.event_listener, event: aeconnect.initial, method: process }

    AE\ConnectBundle\Salesforce\Synchronize\Handlers\BuildFlatMapOfTargets:
        autowire: true
        autoconfigure: true
        tags:
            - { name: kernel.event_listener, event: aeconnect.gather_target_sobjects, method: process }

    AE\ConnectBundle\Salesforce\Synchronize\Handlers\GenerateQueries:
        autowire: true
        autoconfigure: true
        tags:
            - { name: kernel.event_listener, event: aeconnect.generate_queries, method: process, priority: 1 }

    AE\ConnectBundle\Salesforce\Synchronize\Handlers\ModifyQueries:
        autowire: true
        autoconfigure: true
        tags:
            - { name: kernel.event_listener, event: aeconnect.generate_queries, method: process }

    AE\ConnectBundle\Salesforce\Synchronize\Handlers\GetQueryCounts:
        autowire: true
        autoconfigure: true
        tags:
            - { name: kernel.event_listener, event: aeconnect.count_results_from_queries, method: process }

    AE\ConnectBundle\Salesforce\Synchronize\Handlers\ClearSFIDs:
        autowire: true
        autoconfigure: true
        tags:
            - { name: kernel.event_listener, event: aeconnect.clear_sfid, method: process }

    AE\ConnectBundle\Salesforce\Synchronize\Handlers\PullRecords:
        autowire: true
        autoconfigure: true
        tags:
            - { name: kernel.event_listener, event: aeconnect.pull_records, method: process }

    AE\ConnectBundle\Salesforce\Synchronize\Handlers\LocateEntities:
        autowire: true
        autoconfigure: true
        tags:
            - { name: kernel.event_listener, event: aeconnect.locate_entities, method: process }

    AE\ConnectBundle\Salesforce\Synchronize\Handlers\SyncSFIDs:
        autowire: true
        autoconfigure: true
        tags:
            - { name: kernel.event_listener, event: aeconnect.sync_sfids, method: process }

    AE\ConnectBundle\Salesforce\Synchronize\Handlers\UpdateEntityWithSObject:
        autowire: true
        autoconfigure: true
        tags:
            - { name: kernel.event_listener, event: aeconnect.update_entity_with_sobject, method: process }

    AE\ConnectBundle\Salesforce\Synchronize\Handlers\CreateEntityWithSObject:
        autowire: true
        autoconfigure: true
        tags:
            - { name: kernel.event_listener, event: aeconnect.create_entity_with_sobject, method: process }

    AE\ConnectBundle\Salesforce\Synchronize\Handlers\CacheAssociationsForTransformation:
        autowire: true
        autoconfigure: true
        tags:
            - { name: kernel.event_listener, event: aeconnect.transform_associations, method: process, priority: 10 }

    AE\ConnectBundle\Salesforce\Synchronize\Handlers\TransformAssociations:
        autowire: true
        autoconfigure: true
        tags:
            - { name: kernel.event_listener, event: aeconnect.transform_associations, method: process }
            - { name: kernel.event_listener, event: aeconnect.end, method: processSelfReferencedEntities }

    AE\ConnectBundle\Salesforce\Synchronize\Handlers\CustomTransformHandler:
        autowire: true,
        autoconfigure: true,
        tags:
            - { name: kernel.event_listener, event: aeconnect.transform, method: process }

    AE\ConnectBundle\Salesforce\Synchronize\Handlers\ValidateEntities:
        autowire: true
        autoconfigure: true
        tags:
            - { name: kernel.event_listener, event: aeconnect.validate, method: process }

    AE\ConnectBundle\Salesforce\Synchronize\Handlers\ManipulateSequenceGenerator:
        autowire: true
        autoconfigure: true
        tags:
            - { name: kernel.event_listener, event: aeconnect.flush, method: process, priority: 10 }

    AE\ConnectBundle\Salesforce\Synchronize\Handlers\Flush:
        autowire: true
        autoconfigure: true
        tags:
            - { name: kernel.event_listener, event: aeconnect.flush, method: process }

    AE\ConnectBundle\Salesforce\Synchronize\Handlers\OutboundUpdate:
        autowire: true
        autoconfigure: true
        tags:
            - { name: kernel.event_listener, event: aeconnect.outbound_update, method: process }
