services:
    _instanceof:
        AE\ConnectBundle\Salesforce\Transformer\Plugins\TransformerPluginInterface:
            tags:
                - {name: "ae_connect.transformer_plugin"}
    AE\ConnectBundle\Salesforce\Transformer\Transformer: ~
    AE\ConnectBundle\Salesforce\Transformer\TransformerInterface: '@AE\ConnectBundle\Salesforce\Transformer\Transformer'
    AE\ConnectBundle\Salesforce\Transformer\Util\SfidFinder:
        arguments:
            $registry: '@Symfony\Bridge\Doctrine\RegistryInterface'
            $reader: '@Doctrine\Common\Annotations\Reader'
        public: true
    AE\ConnectBundle\Salesforce\Transformer\Util\ConnectionFinder:
        arguments:
            $registry: '@Symfony\Bridge\Doctrine\RegistryInterface'
            $reader: '@Doctrine\Common\Annotations\Reader'
            $logger: '@logger'
        public: true
    AE\ConnectBundle\Salesforce\Transformer\Plugins\CompoundFieldTransformerPlugin: ~
    AE\ConnectBundle\Salesforce\Transformer\Plugins\AssociationTransformer:
        $connectionManager: '@AE\ConnectBundle\Manager\ConnectionManagerInterface'
        $managerRegistry: '@Symfony\Bridge\Doctrine\RegistryInterface'
        $validator: '@Symfony\Component\Validator\Validator\ValidatorInterface'
        $sfidFinder: '@AE\ConnectBundle\Salesforce\Transformer\Util\SfidFinder'
    AE\ConnectBundle\Salesforce\Transformer\Plugins\DateTimeTransformer:
        $registry: '@Symfony\Bridge\Doctrine\RegistryInterface'
    AE\ConnectBundle\Salesforce\Transformer\Plugins\MultiValuePickListTransformer:
        $registry: '@Symfony\Bridge\Doctrine\RegistryInterface'
    AE\ConnectBundle\Salesforce\Transformer\Plugins\RecordTypeTransformer: ~
    AE\ConnectBundle\Salesforce\Transformer\Plugins\UuidTransformerPlugin: ~
    AE\ConnectBundle\Salesforce\Transformer\Plugins\ConnectionEntityTransformer:
        $connectionFinder: '@AE\ConnectBundle\Salesforce\Transformer\Util\ConnectionFinder'
        $logger: '@logger'
    AE\ConnectBundle\Salesforce\Transformer\Plugins\SfidTransformer:
        $registry: '@Symfony\Bridge\Doctrine\RegistryInterface'
        $reader: '@Doctrine\Common\Annotations\Reader'
        $sfidFinder: '@AE\ConnectBundle\Salesforce\Transformer\Util\SfidFinder'
