services:
    _instanceof:
        AE\ConnectBundle\Salesforce\Transformer\Plugins\TransformerPluginInterface:
            tags:
                - {name: "ae_connect.transformer_plugin"}
    AE\ConnectBundle\Salesforce\Transformer\Transformer: ~
    AE\ConnectBundle\Salesforce\Transformer\Plugins\AssociationTransformer:
        $connectionManager: '@AE\ConnectBundle\Manager\ConnectionManagerInterface'
        $managerRegistry: '@Symfony\Bridge\Doctrine\RegistryInterface'
        $referenceGenerator: '@AE\ConnectBundle\Salesforce\Outbound\ReferenceIdGenerator'
        $validator: '@Symfony\Component\Validator\Validator\ValidatorInterface'
    AE\ConnectBundle\Salesforce\Transformer\Plugins\DateTimeTransformer:
        $registry: '@Symfony\Bridge\Doctrine\RegistryInterface'
    AE\ConnectBundle\Salesforce\Transformer\Plugins\MultiValuePickListTransformer:
        $registry: '@Symfony\Bridge\Doctrine\RegistryInterface'
    AE\ConnectBundle\Salesforce\Transformer\Plugins\RecordTypeTransformer: ~
    AE\ConnectBundle\Salesforce\Transformer\Plugins\UuidTransformerPlugin: ~